## import pandas as pd

In [14]:
import pandas as pd
df=pd.read_csv("ddos_attack.csv")
df.head()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,17,49,2,0,458.0,0.0,229.0,229.0,229.0,0.0,...,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NetBIOS
1,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1480,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,LDAP
2,17,1,2,0,458.0,0.0,229.0,229.0,229.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NetBIOS
3,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,LDAP
4,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,LDAP

In [15]:
df.head(10)

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,17,49,2,0,458.0,0.0,229.0,229.0,229.0,0.0,...,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NetBIOS
1,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1480,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,LDAP
2,17,1,2,0,458.0,0.0,229.0,229.0,229.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NetBIOS
3,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,LDAP
4,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,LDAP
5,17,2,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1396,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,LDAP
6,17,49,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1480,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,LDAP
7,17,1,2,0,2848.0,0.0,1424.0,1424.0,1424.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,LDAP
8,17,1,2,0,458.0,0.0,229.0,229.0,229.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NetBIOS
9,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,LDAP

In [16]:
maps = {}
def find_category_mappings(df, variable):
    return {k: i for i, k in enumerate(df[variable].unique())}

def integer_encode(df, variable, ordinal_mapping):
    df[variable] =  df[variable].map(ordinal_mapping)
    maps[variable] = mappings
    
for variable in df.columns:
    if df[variable].dtype == "object":
        mappings = find_category_mappings(df, variable)
        integer_encode(df, variable,  mappings)
        maps[variable] = mappings
maps

{'Label': {'NetBIOS': 0,
  'LDAP': 1,
  'Benign': 2,
  'MSSQL': 3,
  'Portmap': 4,
  'UDP': 5,
  'Syn': 6,
  'UDPLag': 7}}

In [17]:
with open("map.txt", "w") as file:
    file.write(str(maps))

In [18]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1:]

In [19]:
x.head()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,17,49,2,0,458.0,0.0,229.0,229.0,229.0,0.0,...,1,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1,1480,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,17,1,2,0,458.0,0.0,229.0,229.0,229.0,0.0,...,1,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
y.head()

   Label
0      0
1      1
2      0
3      1
4      1

In [21]:
from imblearn.over_sampling import RandomOverSampler# balancing package
ros=RandomOverSampler()

In [22]:
xres,yres = ros.fit_resample(x, y)

In [23]:
x.head()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,17,49,2,0,458.0,0.0,229.0,229.0,229.0,0.0,...,1,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1,1480,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,17,1,2,0,458.0,0.0,229.0,229.0,229.0,0.0,...,1,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
yres.head()

   Label
0      0
1      1
2      0
3      1
4      1

In [25]:
df.iloc[2:3].to_csv('test0.csv')
df.iloc[52:53].to_csv('test1.csv')
df.iloc[67:68].to_csv('test2.csv')
df.iloc[77:78].to_csv('test3.csv')
df.iloc[102:103].to_csv('test4.csv')
df.iloc[149:150].to_csv('test5.csv')
df.iloc[354:355].to_csv('test6.csv')
df.iloc[374:375].to_csv('test7.csv')

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
le=LabelEncoder()
le.fit(y)
y=le.transform(y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

In [28]:
y

array([0, 1, 0, ..., 2, 2, 2], dtype=int64)

In [29]:
from collections import Counter

In [30]:
Counter(y)

Counter({0: 644,
         1: 1906,
         2: 46427,
         3: 8523,
         4: 685,
         5: 18090,
         6: 48840,
         7: 55})

In [31]:
from imblearn.over_sampling import RandomOverSampler

In [32]:
ros = RandomOverSampler(random_state=42)
X_res, y_res = ros.fit_resample(x, y)

In [33]:
Counter(y_res)

Counter({0: 48840,
         1: 48840,
         2: 48840,
         3: 48840,
         4: 48840,
         5: 48840,
         6: 48840,
         7: 48840})

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_res

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,17,49,2,0,458.0,0.0,229.0,229.0,229.0,0.0,...,1,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1,1480,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,17,1,2,0,458.0,0.0,229.0,229.0,229.0,0.0,...,1,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,17,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390715,17,3,2,0,762.0,0.0,381.0,381.0,381.0,0.0,...,1,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
390716,17,3,2,0,664.0,0.0,332.0,332.0,332.0,0.0,...,1,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
390717,17,3,2,0,1162.0,0.0,581.0,581.0,581.0,0.0,...,1,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
390718,17,3,2,0,884.0,0.0,442.0,442.0,442.0,0.0,...,1,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
390719,6,148706,4,2,24.0,12.0,6.0,6.0,6.0,0.0,...,3,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:

x_train,x_test,y_train,y_test=train_test_split(X_res, y_res,train_size=0.8)
x_train.head()

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Act Data Packets,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
303078,17,76,2,0,530.0,0.0,265.0,265.0,265.0,0.0,...,1,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
303768,17,18,2,0,458.0,0.0,229.0,229.0,229.0,0.0,...,1,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
358636,17,2,2,0,1162.0,0.0,581.0,581.0,581.0,0.0,...,1,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
217171,17,50,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
190307,17,1,2,0,2896.0,0.0,1448.0,1448.0,1448.0,0.0,...,1,26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(max_iter=1500)
lr.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(max_iter=1500)

In [38]:
y_pred=lr.predict(x_test)
y_pred

array([3, 3, 0, ..., 0, 6, 0], dtype=int64)

In [39]:
from sklearn.metrics import accuracy_score
ac=accuracy_score(y_test,y_pred)
ac

0.6085559991809992

In [40]:
from sklearn.tree import DecisionTreeClassifier
dtc_clf=DecisionTreeClassifier()
dtc_clf.fit(x_train,y_train)

DecisionTreeClassifier()

In [41]:
y_predict=dtc_clf.predict(x_test)
y_predict

array([3, 7, 0, ..., 4, 6, 0], dtype=int64)

In [42]:
from sklearn.metrics import accuracy_score
ac=accuracy_score(y_test,y_predict)
ac

0.9526003276003276

In [43]:
import joblib

In [44]:
joblib.dump(dtc_clf,"ds1.joblib")

['ds1.joblib']

In [45]:
from sklearn.ensemble import RandomForestClassifier
rmf=RandomForestClassifier(max_depth=3,random_state=0)
rmf_clf=rmf.fit(x_train,y_train)

In [46]:
y_predict1=rmf_clf.predict(x_test)
y_predict1

array([3, 3, 0, ..., 0, 6, 0], dtype=int64)

In [47]:
from sklearn.metrics import accuracy_score
ac1=accuracy_score(y_test,y_predict1)
ac1

0.7248285217035217

# testing

In [48]:
import pandas as pd
from tensorflow.keras.models import load_model
import numpy as np
import joblib

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [49]:

ds=joblib.load("ds1.joblib")

In [50]:
d1=pd.read_csv("test3.csv")
d1

,Unnamed: 0,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,77,17,1,2,0,2912.0,0.0,1456.0,1456.0,1456.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [51]:
df1=d1.iloc[:,1:-1]

In [52]:
pred=ds.predict(df1)
pred[0]

1

In [53]:

if pred[0]==0:
        out='NetBIOS'
elif pred[0]==1:
        out='LDAP'
elif pred[0]==2:
        out='Benign'
elif pred[0]==3:
        out='MSSQL'
elif pred[0]==4:
        out='Portmap' 
elif pred[0]==5:
        out='UDP' 
elif pred[0]==6:
        out='Syn' 
elif pred[0]==7:
        out='UDPLag'         
print(out)

LDAP